/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Check a password and log the browser in.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Log the browser out.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who is logged in.
         *
         *     With authentication disabled there is no user to describe, so a placeholder is returned
         *     rather than a 401 the UI would read as "log in".
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browser/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Close Login
         * @description Abandon a login session without saving it.
         */
        delete: operations["close_login_api_browser__token__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/browser/{token}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Session
         * @description Store the session the live browser is holding, then close it.
         */
        post: operations["save_session_api_browser__token__save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index
         * @description The most recent checks across all sites, newest first.
         */
        get: operations["index_api_checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report that the process is up and its database is reachable.
         *
         *     Unauthenticated, and it touches the database rather than only returning a constant: a
         *     container that answers while its database is unopenable is not healthy, and a probe
         *     that cannot tell the difference is worse than none.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show
         * @description The current settings.
         */
        get: operations["show_api_settings_get"];
        /**
         * Update
         * @description Replace the settings.
         */
        put: operations["update_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/test-notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Notification
         * @description Send a test message to every configured destination.
         */
        post: operations["test_notification_api_settings_test_notification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * State
         * @description Whether this instance still needs an administrator.
         */
        get: operations["state_api_setup_get"];
        put?: never;
        /**
         * Complete
         * @description Create the administrator and log the browser in.
         *
         *     Guarded by a token printed to the container's log. This instance may be reachable from
         *     the internet before anyone has configured it, and without the token whoever found the
         *     URL first would own it.
         */
        post: operations["complete_api_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index
         * @description Every site, with the recent history the list displays.
         */
        get: operations["index_api_sites_get"];
        put?: never;
        /**
         * Create
         * @description Add a site.
         */
        post: operations["create_api_sites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show
         * @description One site.
         */
        get: operations["show_api_sites__site_id__get"];
        /**
         * Update
         * @description Change a site's configuration.
         */
        put: operations["update_api_sites__site_id__put"];
        post?: never;
        /**
         * Destroy
         * @description Remove a site, its stored session and its history.
         */
        delete: operations["destroy_api_sites__site_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Now
         * @description Ping a site immediately and return the result.
         */
        post: operations["check_now_api_sites__site_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description A site's recent checks, newest first.
         */
        get: operations["history_api_sites__site_id__checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect
         * @description Work out how to tell this site's live session from a dead one.
         *
         *     Fetches the ping URL twice, once with the stored session and once with no cookies, and
         *     reports what differs. Needs a session, because half the comparison is what the page looks
         *     like to somebody who is logged in.
         */
        post: operations["detect_api_sites__site_id__detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/login-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open Login
         * @description Start a browser at the site's login page and stream its screen.
         */
        post: operations["open_login_api_sites__site_id__login_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Forget Session
         * @description Discard a site's stored session.
         */
        delete: operations["forget_session_api_sites__site_id__session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/session/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Session
         * @description Store a session pasted in by hand.
         */
        post: operations["import_session_api_sites__site_id__session_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CaptureMethod
         * @description Where a stored session came from.
         * @enum {string}
         */
        CaptureMethod: "browser" | "import";
        /**
         * CheckOutcome
         * @description What one ping established.
         * @enum {string}
         */
        CheckOutcome: "ok" | "login_expired" | "pattern_missing" | "http_error" | "network_error";
        /**
         * CheckRead
         * @description One entry of a site's history.
         */
        CheckRead: {
            /** Detail */
            detail: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Final Url */
            final_url: string | null;
            /** Id */
            id: number;
            outcome: components["schemas"]["CheckOutcome"];
            /** Site Id */
            site_id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status Code */
            status_code: number | null;
        };
        /**
         * CookieImport
         * @description A session pasted in by hand.
         */
        CookieImport: {
            /** Text */
            text: string;
            /** User Agent */
            user_agent?: string | null;
        };
        /**
         * DetectedRules
         * @description What a signed-in and a signed-out fetch of the same page suggest.
         *
         *     Offered rather than applied: these are a starting point someone reads and corrects, and a
         *     rule that silently appeared is a rule nobody knows is there.
         */
        DetectedRules: {
            /** Failure Pattern */
            failure_pattern?: string | null;
            /** Login Url Pattern */
            login_url_pattern?: string | null;
            /**
             * Notes
             * @default []
             */
            notes: string[];
            /** Success Pattern */
            success_pattern?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description A login attempt.
         */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * LoginSessionRead
         * @description A live interactive-login session.
         */
        LoginSessionRead: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Height */
            height: number;
            /** Site Id */
            site_id: number;
            /** Width */
            width: number;
            /** Ws Path */
            ws_path: string;
        };
        /**
         * Message
         * @description A plain result for actions that have nothing else to say.
         */
        Message: {
            /** Detail */
            detail: string;
        };
        /**
         * PingMethod
         * @description How a site is pinged.
         * @enum {string}
         */
        PingMethod: "http" | "browser";
        /**
         * SessionRead
         * @description What is known about a stored session, without any of its secrets.
         */
        SessionRead: {
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            captured_via: components["schemas"]["CaptureMethod"];
            /** Cookie Names */
            cookie_names: string[];
            /** Expires At */
            expires_at: string | null;
            /** Rotated At */
            rotated_at: string | null;
        };
        /**
         * SettingsRead
         * @description The instance settings, as returned.
         */
        SettingsRead: {
            /**
             * Apprise Urls
             * @default
             */
            apprise_urls: string;
            /**
             * Browser Idle Timeout Minutes
             * @default 15
             */
            browser_idle_timeout_minutes: number;
            /**
             * Default Interval Days
             * @default 7
             */
            default_interval_days: number;
            /**
             * Error Threshold
             * @default 3
             */
            error_threshold: number;
            /**
             * Log Level
             * @default INFO
             * @enum {string}
             */
            log_level: "DEBUG" | "INFO" | "WARNING" | "ERROR";
            /**
             * Notify Cooldown Hours
             * @default 24
             */
            notify_cooldown_hours: number;
            /**
             * Notify On Cookie Expiry
             * @default true
             */
            notify_on_cookie_expiry: boolean;
            /**
             * Notify On Deadline
             * @default true
             */
            notify_on_deadline: boolean;
            /**
             * Notify On Errors
             * @default true
             */
            notify_on_errors: boolean;
            /**
             * Notify On Lapsed
             * @default true
             */
            notify_on_lapsed: boolean;
            /**
             * Notify On Recovered
             * @default true
             */
            notify_on_recovered: boolean;
            /**
             * Retention Days
             * @default 90
             */
            retention_days: number;
            /**
             * Warning Lead Days
             * @default 7
             */
            warning_lead_days: number;
        };
        /**
         * SettingsWrite
         * @description The instance settings a client may change.
         */
        SettingsWrite: {
            /**
             * Apprise Urls
             * @default
             */
            apprise_urls: string;
            /**
             * Browser Idle Timeout Minutes
             * @default 15
             */
            browser_idle_timeout_minutes: number;
            /**
             * Default Interval Days
             * @default 7
             */
            default_interval_days: number;
            /**
             * Error Threshold
             * @default 3
             */
            error_threshold: number;
            /**
             * Log Level
             * @default INFO
             * @enum {string}
             */
            log_level: "DEBUG" | "INFO" | "WARNING" | "ERROR";
            /**
             * Notify Cooldown Hours
             * @default 24
             */
            notify_cooldown_hours: number;
            /**
             * Notify On Cookie Expiry
             * @default true
             */
            notify_on_cookie_expiry: boolean;
            /**
             * Notify On Deadline
             * @default true
             */
            notify_on_deadline: boolean;
            /**
             * Notify On Errors
             * @default true
             */
            notify_on_errors: boolean;
            /**
             * Notify On Lapsed
             * @default true
             */
            notify_on_lapsed: boolean;
            /**
             * Notify On Recovered
             * @default true
             */
            notify_on_recovered: boolean;
            /**
             * Retention Days
             * @default 90
             */
            retention_days: number;
            /**
             * Warning Lead Days
             * @default 7
             */
            warning_lead_days: number;
        };
        /**
         * SetupRequest
         * @description The first-run wizard's submission.
         */
        SetupRequest: {
            /** Password */
            password: string;
            /** Token */
            token?: string | null;
            /** Username */
            username: string;
        };
        /**
         * SetupState
         * @description Whether this instance still needs configuring.
         */
        SetupState: {
            /** Setup Required */
            setup_required: boolean;
            /** Token Required */
            token_required: boolean;
        };
        /**
         * SiteRead
         * @description A site as the UI shows it.
         */
        SiteRead: {
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Deadline At */
            deadline_at: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Expected Status
             * @default 200
             */
            expected_status: number;
            /** Failure Pattern */
            failure_pattern?: string | null;
            /** Favicon */
            favicon?: string | null;
            /**
             * Follow Redirects
             * @default true
             */
            follow_redirects: boolean;
            /** Id */
            id: number;
            /** Inactivity Limit Days */
            inactivity_limit_days?: number | null;
            /**
             * Interval Days
             * @default 7
             */
            interval_days: number;
            /**
             * Jitter Percent
             * @default 10
             */
            jitter_percent: number;
            /** Last Check At */
            last_check_at: string | null;
            /** Last Ok At */
            last_ok_at: string | null;
            /** Login Url */
            login_url?: string | null;
            /** Login Url Pattern */
            login_url_pattern?: string | null;
            /** Name */
            name: string;
            /** Next Check At */
            next_check_at: string | null;
            /** Notes */
            notes?: string | null;
            /** @default http */
            ping_method: components["schemas"]["PingMethod"];
            /** Ping Url */
            ping_url: string;
            /** Pulse */
            pulse?: components["schemas"]["CheckOutcome"][];
            /** Risk */
            risk?: string | null;
            session?: components["schemas"]["SessionRead"] | null;
            status: components["schemas"]["SiteStatus"];
            /** Success Pattern */
            success_pattern?: string | null;
            /** User Agent */
            user_agent?: string | null;
        };
        /**
         * SiteStatus
         * @description How a site's session looked at its most recent check.
         * @enum {string}
         */
        SiteStatus: "unknown" | "alive" | "at_risk" | "lapsed" | "error";
        /**
         * SiteWrite
         * @description What a client may set on a site.
         */
        SiteWrite: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Expected Status
             * @default 200
             */
            expected_status: number;
            /** Failure Pattern */
            failure_pattern?: string | null;
            /**
             * Follow Redirects
             * @default true
             */
            follow_redirects: boolean;
            /** Inactivity Limit Days */
            inactivity_limit_days?: number | null;
            /**
             * Interval Days
             * @default 7
             */
            interval_days: number;
            /**
             * Jitter Percent
             * @default 10
             */
            jitter_percent: number;
            /** Login Url */
            login_url?: string | null;
            /** Login Url Pattern */
            login_url_pattern?: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** @default http */
            ping_method: components["schemas"]["PingMethod"];
            /** Ping Url */
            ping_url: string;
            /** Success Pattern */
            success_pattern?: string | null;
            /** User Agent */
            user_agent?: string | null;
        };
        /**
         * UserRead
         * @description Who is logged in.
         */
        UserRead: {
            /** Id */
            id: number;
            /** Last Login At */
            last_login_at: string | null;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    close_login_api_browser__token__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_session_api_browser__token__save_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_api_checks_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    show_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
        };
    };
    update_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_notification_api_settings_test_notification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    state_api_setup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupState"];
                };
            };
        };
    };
    complete_api_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_api_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"][];
                };
            };
        };
    };
    create_api_sites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    show_api_sites__site_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_sites__site_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    destroy_api_sites__site_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_now_api_sites__site_id__check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_sites__site_id__checks_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_api_sites__site_id__detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectedRules"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_login_api_sites__site_id__login_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forget_session_api_sites__site_id__session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_session_api_sites__site_id__session_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CookieImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
